config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: "portfolio_show"
  get 'angular-items', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do 
        get :toggle_status
    end
  end


  root to: 'pages#home'

end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50">
  <p><%= @copyright %></p>
</footer>

app/views/shared/_application_nav.html.erb
<div>
  <h3 class="float-md-start mb-0">MTalk</h3>
  <nav class="nav nav-masthead justify-content-center float-md-end app-nav">
    <%= nav_helper 'nav-link', 'span' %>
    <%= login_helper 'nav-link' %>

  </nav>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= @copyright %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Blog</h1>
    <p class="lead blog-description">An example temple built with Bootstrap.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>     
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Junior Ruby Developer from Poland, EU</p>
  </div>

  <div class="sidebar-module">
    <h4>Find me on</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
 <div><%= link_to "Home", root_path %></div>
 <div><%= link_to "About", about_me_path %></div>
 <div><%= link_to "Contact", contact_path %></div>
 <div><%= link_to "Blog", blogs_path %></div>
 <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p>
      <%= @copyright %>
    </p>
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">Below it's my portfolio items</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Junior Ruby Dev</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <li><%= link_to "Home", root_path, class: "text-white" %></li>
            <li><%= link_to "About", about_me_path, class: "text-white" %></li>
            <li><%= link_to "Contact", contact_path, class: "text-white" %></li>
            <li><%= link_to "Blog", blogs_path, class: "text-white" %></li>
            <li><%= link_to "Portfolio", portfolios_path, class: "text-white" %></li>
            <li><%= login_helper 'text-white' %></li>
          </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <svg xmlns="https://place-hold.it/300x250" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
      <strong>MTalk</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>